= 「尾野（狐）」の利用ガイドライン

以下を「該当コンテンツ」と称します。

* 株式会社シテイルPRキャラクター「尾野（狐）」
* Youtubeシテイルチャンネルの動画及び画像
* Youtubeシテイルチャンネルに登場する範囲での「田中ぽっきー」

ただし以下を含みません

* 他の著作者から提供され、該当コンテンツ内で紹介した作品

該当コンテンツの著作権保持者は以下となります

* 株式会社シテイル

== 該当コンテンツ利用の許可

以下の禁止事項の何れかに当てはまらない限り、該当コンテンツは、無加工・加工、商用・非商用、個人・法人、2D・3Dに関わらず、該当コンテンツ及びそれを模した作品に関して、該当コンテンツの著作権保持者に対し無許可かつ無償で利用することが出来ます。

== 禁止事項

=== 引用の範囲を超えての無加工での利用

該当コンテンツを無加工のまま、引用の範囲を超えて利用する場合は許可されません。footnote:[主に該当コンテンツ全体の無断転載がこれにあたります。]

引用の定義については日本国内の判例footnote:[link:https://ja.wikipedia.org/wiki/%E5%BC%95%E7%94%A8[判例]]に従ったものになります。

なお該当コンテンツの一場面の静止画と、模した作品に関してはこの禁止事項にあたりません。

=== 公式作品と誤認させる利用

該当コンテンツを利用することで、それを含む作品が、著作権保持者による作品と第三者に誤認させるような利用は禁止します。以下の１つでも満たす場合は、公式作品と誤認させていないと判断します。

* 第三者が必ず目にする場所に、公式作品ではないことを明記する。
* 一般的な引用の範囲内。
* 自身で描いたイラストなど、明らかにキャラクターを模して作られたと一般的に認識される著作物。footnote:[ただし、他人が作成した該当コンテンツに模した著作物は、作成した人間の著作権にも注意が必要です。]
* その他、一般的な常識として、公式作品と誤認しないと考えられる場合。

== 問い合わせによる許可を得た利用

禁止事項に当てはまる場合でも、著作者に許可を得ることで利用することができます。ただし、禁止事項に当てはまらない場合、問い合わせに対して許可を出すことができません。footnote:[ガイドラインを用意したにも関わらず、結果的に許可を得て利用することを推奨してしまうことになるからです。]

また、禁止事項に当てはまるかどうか質問されても回答出来ない場合があります。

== 利用における責任

該当コンテンツを利用したことによるあらゆる保証はありません。著作権保持者は、契約行為、不正行為、またはそれ以外の行為において、該当コンテンツの使用に起因、関連する事項、使用によって生じる一切の請求、損害、その他の義務について責任を負わないものとします。

== ガイドラインの変更

このガイドラインは通知なく変更されることがあります。ガイドラインが変更されても、過去に公開された利用に対し、遡って適用されることはありません。
