= 尾野（狐）の利用ガイドライン

以下は株式会社シテイルPRキャラクター「尾野（狐）」（以下、尾野狐）と、株式会社シテイルが提供する尾野狐の含まれた動画・画像（以下、公式作品）、及び尾野狐を模して作られた書籍や立体物を含む作品（以下、模した作品）に関しての利用ガイドラインになります。他の著作者からの提供作品や尾野狐ではないキャラクターには適用されません。ただし、公式作品に登場する「田中ぽっきー」に関して、動画内に登場する範囲においては尾野狐と同じ扱いを受けるものとします。

== 無許可での利用

無加工・加工、商用・非商用、個人・法人に関わらず、公式作品及び模した作品に関して、無許可かつ無償で利用することが出来ます。ただし、以下の禁止事項の何れかに当てはまる場合は許可できません。

=== 禁止事項

==== 引用の範囲を超えての動画の利用

動画が主体となる形で、引用の範囲を超えて利用する場合は許可されません。主に動画そのものの無断転載がこれにあたります。

引用の定義についてはlink:https://ja.wikipedia.org/wiki/%E5%BC%95%E7%94%A8[判例]に従ったものになります。

なお公式作品の一部を切り抜いた静止画と、模した作品に関してはこの禁止事項にあたりません。

==== 公式作品と誤認させる利用

尾野狐のキャラクターを利用することで、それを含む作品が、公式作品と第三者に誤認させるような利用は禁止します。

以下の１つでも満たす場合は、公式作品と誤認させていないと判断します。

* 第三者が必ず目にする場所に、公式作品ではないことを明記する。
* 動画や画像などを、一般的な引用の範囲内。
* 自身で描いたイラストなど、明らかにキャラクターを模して作られたと一般的に認識される著作物。footnote:[ただし、他人が描いたイラストの場合は、作成した人間の著作権にも注意が必要です。]
* 世間一般的な常識として、公式作品と誤認しないと考えられる場合。

== 許可を得た利用

「無許可での利用」に当てはまらない場合でも、許可を得ることで利用することができます。ただし、「無許可での利用」に当てはまる場合には、問い合わせに対して許可を出すことができません。footnote:[「無許可での利用」のガイドラインを用意したにも関わらず、結果的に許可を得て利用することを推奨してしまうことになるからです。「無許可での利用」に当てはまるかどう質問されても回答出来ない場合があります。]

== 利用における責任

尾野狐を利用するにあたり、株式会社シテイルはなんら責任を負いません。

== ガイドラインの変更

このガイドラインはgitHubにコミットされた日時で作成されたものです。ガイドラインは通知なく変更されることがあります。

ガイドラインが変更されても、過去に公開された利用に対して遡って適用されることはありません。
